networks:
    encore-api:
        name: 'encore-api'
    postgresql_encore-api:
        name: 'postgresql_encore-api'
services:
    encore-api:
        container_name: 'encore-api'
        depends_on:
            postgresql:
                condition: 'service_healthy'
        env_file: './Encore-API/.env'
        healthcheck:
            interval: '30s'
            retries: 5
            start_period: '60s'
            test: ['CMD-SHELL', 'curl -fsS http://localhost:8080/api/v1/health > /dev/null']
            timeout: '5s'
        image: 'kissalexandra/encore-api:1.0.0'
        networks:
            - 'encore-api'
            - 'postgresql_encore-api'
        ports:
            - '8080:8080/tcp'
        restart: 'unless-stopped'
        volumes:
            - './Encore-API/Storage/:/app/Storage/:rw'
    postgresql:
        container_name: 'postgresql'
        env_file: './PostgreSQL/.env'
        healthcheck:
            interval: '10s'
            retries: 5
            start_period: '30s'
            test: ['CMD-SHELL', 'pg_isready -q -U encore -d encore']
            timeout: '5s'
        image: 'postgres:18.6'
        networks:
            - 'postgresql_encore-api'
        ports:
            - '127.0.0.1:5432:5432/tcp'
        restart: 'unless-stopped'
        volumes:
            - './PostgreSQL/data/:/var/lib/postgresql/:rw'
